### ISSUE TITLE
add timeout to blocking read functions

### ISSUE THREAD

**Issue by TomW1605** [CoreElectronics/CE-PiicoDev-RFID-MicroPython-Module#1]
many of the read functions will block till they see a card. this can be useful but is also a pain if the card is there long enough to pass a presence test in an if but then removed before the read function can check it. it would be good if these while loops could time out after a given delay. here is an example of a modified readText that implaments this timeout:
![image](https://user-images.githubusercontent.com/17092573/202662283-ffcd5480-d8b5-467f-97d7-191f91259dfa.png)

**Comment by graham-mitchell-vcs** [comment]
Thanks @TomW1605 - this is worth a look in!

What real-world scenario are you catering for, am curious?

**Comment by TomW1605** [comment]
> What real-world scenario are you catering for, am curious?

i have found that it will block indefinatly if the card it removed too soon.
eg if you change the example in the readme if you change `rfid.readId()` to `rfid.readText()` (a verry reasonable thing to do) and then scan a card too fast it will pass the `if rfid.tagPresent()` check but then get stuck in the loop in `readText()` because it is no longer there. same thing if the card is removed mid read.

i am trying to make a basic tag in/tag out system and have found some people are not leaving there tags there long enough and casuing the whole system to hang. so i guess im catering for "rushed and uninformed users"

**Comment by graham-mitchell-vcs** [comment]
Thanks for that context @TomW1605 

@CoreProduction @CoreProduction2 could you please explore a timeout as an optional argument

**Comment by CoreProduction** [comment]
@TomW1605 Thanks for this improvement - We'll implement this suggestion

**Comment by CoreProduction** [comment]
Commit [16eb4ab](https://github.com/CoreElectronics/CE-PiicoDev-RFID-MicroPython-Module/commit/16eb4ab2b63d7b8cde5ed72d036bfb14760d06a0) addresses `readText()` robustness. The timeout is implemented and if a tag is removed before a string is read completely, the partial string will be returned. 
The commit is available to anybody downloading `PiicoDev_RFID_Expansion.py` now, and will be rolled out in the PyPI package for Raspberry Pi later today.

Here's what that looks like for the user:


![image](https://user-images.githubusercontent.com/73618042/203660158-da1becca-4cf0-4d7d-aa43-855e773285f0.png)
