### ISSUE TITLE
Clone keys

### ISSUE THREAD

**Issue by mlucchelli** [CoreElectronics/CE-PiicoDev-RFID-MicroPython-Module#2]
Hello! I lost the copy of my keys and I want to clone mine for my mother.

How can I clone my current key using this module?

Regards

**Comment by CoreProduction** [comment]
Hi Mario
There is currently no implementation for the PiicoDev RFID reader to write new IDs to a key. It only has read access to the ID, and read/write access to the EEPROM.

If the key you wish to copy uses data in the EEPROM as an identifier then you can use the write functions as described in the [tutorial](https://core-electronics.com.au/guides/raspberry-pi-pico/piicodev-rfid-module-guide-for-raspberry-pi-pico/).
