### ISSUE TITLE
Not working on Pi3B

### ISSUE THREAD

**Issue by JanguRow** [CoreElectronics/CE-PiicoDev-RFID-MicroPython-Module#3]
I've been trying to get this to work on model 3b, and for some reason, the loop takes up 20 seconds to attempt to read something I'm using the same code as on the website with the latest install for me piicodev 1.10.0 after some debugging it's hanging on the `rfid.tagPresent()` call not sure why though. I've tried this on Raspberry Pi OS  64 bit and 32 bit including legacy version and still have no luck any help would be great

``` python
from PiicoDev_RFID import PiicoDev_RFID
from PiicoDev_Unified import sleep_ms

rfid = PiicoDev_RFID()   # Initialise the RFID module

print('Place tag near the PiicoDev RFID Module')

while True:    
    if rfid.tagPresent():    # if an RFID tag is present <--- hanging here
        id = rfid.readID()   # get the id
#         id = rfid.readID(detail=True) # gets more details eg. tag type

        print(id)            # print the id

    sleep_ms(100)

```

**Comment by JanguRow** [comment]
tried switching to the raspberry pi zero 2 w and it still does the same hanging problem

**Comment by CoreProduction** [comment]
It sounds like your unit might be faulty - please reach out to support@coreelectronics.com.au or reply to your order confirmation email.
